# Reference: https://starship.rs/zh-CN/config/
# 在 shell 提示符之间插入空行
add_newline = false

format = """
$os\
$all\
$fill\
$cmd_duration\
$line_break\
$jobs\
$battery\
$container\
$character
"""

# 右侧提示和输入区显示在同一行
right_format = """
$time\
""" 

[c]
symbol = " "
format = "[$symbol($version(-$name) )]($style)"

[character]
format = "$symbol"
success_symbol = "[❯](bold green) "
error_symbol = "[✗](bold red) "
vimcmd_symbol	= "[❮](bold yellow) "

[cmake]
symbol = "△ "
format = "[$symbol($version )]($style)"

[cmd_duration]
min_time = 0
show_milliseconds	= true
format = "took [$duration](bold yellow)"

[conda]
symbol = "🅒  "
format = "[$symbol$environment](bold green)"

[container]
symbol = " "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[docker_context]
symbol = " "
format = "[$symbol$context]($style)"

[fill]
symbol = " "

[git_branch]
symbol = ""
format = "[$symbol$branch(:$remote_branch)]($style)"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[golang]
symbol = " "
format = "[$symbol($version )]($style)"

[java]
symbol = " "
format = "[${symbol}(${version} )]($style)"

[jobs]
symbol = "󰁯 "

[lua]
symbol = " "
format = "via [$symbol($version )]($style)"

[nodejs]
symbol = ""
format = "[$symbol($version )]($style)"

[os]
disabled = false
[os.symbols]
Amazon = " "
Android = " "
Arch = "󰣇 "
Debian = " "
Fedora = " "
Garuda = " "
Linux = " "
Macos = " "
Manjaro = " "
Raspbian = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rlang]
symbol = " "
format = "[$symbol($version )]($style)"

[rust]
symbol = ""
format = "[$symbol($version )]($style)"

[time]
disabled = false
format = "[$time]($style)"
